version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:16.3.0
commands:
  restore_npm:
    steps:
      - restore_cache:
          name: "npmの依存関係を復元する"
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
  save_npm:
    steps:
      - save_cache:
          name: "npmの依存関係をキャッシュする"
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/workspace/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: "依存関係をインストールする"
          command: npm install
      - save_npm

  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: "プロジェクトのnpmパッケージをインストール"
          command: npm install
      - run:
          name: "lintチェック"
          command: npm run lint
      - run:
          name: "ソースコードのビルド"
          command: npm run build
      - run:
          name: "単体テストを実行"
          command: npm run test

workflows:
  version: 2
  setup_and_deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
