version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.3.0
    steps:
      - setup_remote_docker
      - run:
          name: "docker imageを永続化する"
          command: |
            mkdir -p /tmp/docker
            docker save circleci/node:16.3.0 -o /tmp/docker/image
      - persist_to_workspace:
          root: /tmp/docker
          paths:
            - image

  test:
    requires:
      - build
    docker:
      - image: circleci/node:16.3.0
    steps:
      - attach_workspace:
          at: /tmp/docker
            - setup_remote_docker
            - run: docker load -i /tmp/docker/image
      - checkout
      - run:
          name: "プロジェクトのnpmパッケージをインストール"
          command: npm install
      - run:
          name: "lintチェック"
          command: npm run lint
      - run:
          name: "ソースコードのビルド"
          command: npm run build
      - run:
          name: "単体テストを実行"
          command: npm run test

workflows:
  build_and_test:
    jobs:
      - build
      - test
