version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.3.0
    steps:
      - checkout
      - run:
          name: "プロジェクトのnpmパッケージをインストール"
          command: npm install
      - run:
          name: "lintチェック"
          command: npm run lint
      - run:
          name: "ソースコードのビルド"
          command: npm run build

  test:
    docker:
      - image: circleci/node:16.3.0
    steps:
      - checkout
      - run:
          name: "プロジェクトのnpmパッケージをインストール"
          command: npm install
      - run:
          name: "lintチェック"
          command: npm run lint
      - run:
          name: "ソースコードのビルド"
          command: npm run build
      - run:
          name: "単体テストを実行"
          command: npm run test

workflows:
  build_and_test:
    jobs:
      - build
      - test
