export const LOG_TYPE = {
  START: 'START',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PROCESS: 'PROCESS',
  START_CRAWLING: 'START CRAWLING',
  SUCCESS_CRAWLING: 'SUCCESS CRAWLING',
  PROCESS_CRAWLING: 'PROCESS CRAWLING',
  FAILED_CRAWLING: 'FAILED CRAWLING',
  START_DB_IO: 'START DB I/0',
  SUCCESS_DB_IO: 'SUCCESS DB I/0',
  PROCESS_DB_IO: 'PROCESS DB I/0',
  FAILED_DB_IO: 'FAILED DB I/0',
} as const;
